# Generated by Django 4.2.10 on 2024-02-29 08:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    replaces = [
        ("subscription", "0001_initial"),
        ("subscription", "0002_subscription_last_notification_time"),
        ("subscription", "0003_subscription_is_enabled"),
        ("subscription", "0004_alter_subscription_unique_together"),
    ]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("city", models.CharField(max_length=50)),
                ("notification_period", models.PositiveIntegerField(default=24)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "last_notification_time",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("is_enabled", models.BooleanField(default=True)),
            ],
            options={
                "unique_together": {("user", "city")},
            },
        ),
    ]
